// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CornerStore.Migrations
{
    [DbContext(typeof(CornerStoreDbContext))]
    partial class CornerStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CornerStore.Models.Cashier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cashiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Will",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Chloe",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mike",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Hillary",
                            LastName = "West"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Snack"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Drink"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Meal"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Household"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CashierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CashierId = 2,
                            PaidOnDate = new DateTime(2024, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CashierId = 1,
                            PaidOnDate = new DateTime(2024, 1, 13, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CashierId = 4,
                            PaidOnDate = new DateTime(2024, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CashierId = 3,
                            PaidOnDate = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CornerStore.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Frito-Lay",
                            CategoryId = 1,
                            Price = 2.99m,
                            ProductName = "Doritos"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "General Mills",
                            CategoryId = 1,
                            Price = 3.99m,
                            ProductName = "Chex Mix"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Frito-Lay",
                            CategoryId = 1,
                            Price = 2.99m,
                            ProductName = "Cheetos"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Coca-Cola",
                            CategoryId = 2,
                            Price = 3.99m,
                            ProductName = "Coke"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Coca-Cola",
                            CategoryId = 2,
                            Price = 3.99m,
                            ProductName = "Diet Coke"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Monster Beverage Corporation",
                            CategoryId = 2,
                            Price = 2.99m,
                            ProductName = "Monster Energy"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Nestle Global",
                            CategoryId = 3,
                            Price = 8.99m,
                            ProductName = "Digiorno Pizza"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Twice Daily",
                            CategoryId = 3,
                            Price = 5.99m,
                            ProductName = "Ham & American Cheese Sandwich"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Downy",
                            CategoryId = 4,
                            Price = 4.99m,
                            ProductName = "Paper Towels"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Duracell",
                            CategoryId = 4,
                            Price = 1.99m,
                            ProductName = "Batteries"
                        });
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.HasOne("CornerStore.Models.Cashier", "Cashier")
                        .WithMany("Orders")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("CornerStore.Models.OrderProduct", b =>
                {
                    b.HasOne("CornerStore.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CornerStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CornerStore.Models.Product", b =>
                {
                    b.HasOne("CornerStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CornerStore.Models.Cashier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CornerStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CornerStore.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
